server:
  port: 8899
spring:
  mvc:
    view:
      prefix: /static/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_security_demo
