server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql:///million_data?characterEncoding=utf-8&serverTimezone=UTC
  cache:
#    type: ehcache
    type: REDIS
    ehcache:
      config: classpath:ehcache-setting.xml
  redis:
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.chcache.com.security.session.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
